### ISSUE TITLE
seed-init-service upload.py and download.py no longer needed

### ISSUE THREAD

**Issue by santi-ifontana** [commerceblock/terraform-services#1]
The files [download.py](https://github.com/commerceblock/terraform-services/blob/main/seed-init-service/download.py) & [upload.py](https://github.com/commerceblock/terraform-services/blob/main/seed-init-service/upload.py) are no longer needed since they are implemented in the startup script of each VM. Maybe we can delete them.

**Comment by santi-ifontana** [comment]
@rk16449

**Comment by rk16449** [comment]
No longer needed, but we can keep this as a reference
